#!/usr/bin/env bash
set -Eeuo pipefail

# === Repo paths ===
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
EXAMPLES_MACROS="${REPO_ROOT}/examples/builder_macros.cfg"

# === System paths (we don't modify repo structure) ===
CFG_DIR="${HOME}/printer_data/config"
PRINTER_CFG="${CFG_DIR}/printer.cfg"
BUILDER_CFG="${CFG_DIR}/builder.cfg"
BUILDER_MACROS="${CFG_DIR}/builder_macros.cfg"

echo "== macro-builder installer =="

# -------------------------------------------------
# 1) PRE-CHECKS: gcode_shell_command + Katapult
# -------------------------------------------------

# 1.a) gcode_shell_command (Klipper extra)
if [[ ! -f "${HOME}/klipper/klippy/extras/gcode_shell_command.py" ]]; then
  echo "ERROR: Klipper does not have 'gcode_shell_command'."
  echo "-> Update Klipper via Web UI (Machine > Updates) or KIAUH, then retry."
  exit 1
fi

# 1.b) Katapult present with flashing scripts
KATA_DIR="${HOME}/katapult"
HAS_FLASH_CAN=false
HAS_FLASH_USB=false

if [[ -f "${KATA_DIR}/scripts/flash_can.py" ]]; then HAS_FLASH_CAN=true; fi
# Accept either flashtool.py (preferred upstream) or legacy flashtool.py
if [[ -f "${KATA_DIR}/scripts/flashtool.py" ]] || [[ -f "${KATA_DIR}/scripts/flashtool.py" ]]; then HAS_FLASH_USB=true; fi

if [[ ! -d "${KATA_DIR}" || "${HAS_FLASH_CAN}" != true || "${HAS_FLASH_USB}" != true ]]; then
  echo "ERROR: Katapult is not installed correctly."
  echo "-> Install with:"
  echo "     git clone https://github.com/Arksine/katapult.git ~/katapult"
  echo "   Ensure these exist:"
  echo "     ~/katapult/scripts/flash_can.py"
  echo "     ~/katapult/scripts/flashtool.py   # or legacy flashtool.py"
  exit 1
fi

echo "[1/6] OK: gcode_shell_command and Katapult detected."

# Ensure user config dir exists
mkdir -p "${CFG_DIR}"

# -------------------------------------------------
# 4) Install builder_macros.cfg from examples and include it
# -------------------------------------------------
if [[ ! -f "${EXAMPLES_MACROS}" ]]; then
  echo "ERROR: Missing examples/builder_macros.cfg in the repository."
  exit 1
fi

# Copy the example macros file to the user's config
cp -f "${EXAMPLES_MACROS}" "${BUILDER_MACROS}"

# Auto-include at the top of printer.cfg
if [[ ! -f "${PRINTER_CFG}" ]]; then
  echo "# Autogenerated printer.cfg header" > "${PRINTER_CFG}"
fi
if ! grep -qE '^\s*\[include\s+builder_macros\.cfg\]\s*$' "${PRINTER_CFG}"; then
  cp -f "${PRINTER_CFG}" "${PRINTER_CFG}.bak.$(date +%s)"
  printf "[include builder_macros.cfg]\n\n%s" "$(cat "${PRINTER_CFG}")" > "${PRINTER_CFG}"
  echo "[4/6] Installed builder_macros.cfg from examples and included it at the top of printer.cfg (backup created)."
else
  echo "[4/6] builder_macros.cfg installed from examples; printer.cfg already includes it."
fi

# -------------------------------------------------
# 3) + 5) Create builder.cfg (EN) with examples
# -------------------------------------------------
cp -f "${BUILDER_CFG}" "${BUILDER_CFG}.bak.$(date +%s)" 2>/dev/null || true
cat > "${BUILDER_CFG}" <<'EOF'
# =========================
# macro-builder: builder.cfg
# =========================
# This single config drives BOTH builders:
#   - [klipper <NAME>] sections build Klipper firmwares
#   - [katapult <NAME>] sections build Katapult bootloaders
#
# Fields (per section):
#   name:              Friendly name for the artifact/versioned file names.
#   config:            Either a bare filename searched under:
#                        ~/macro-builder/configs/klipper/   (for [klipper ...])
#                        ~/macro-builder/configs/katapult/  (for [katapult ...])
#                      or any path (absolute, or relative to the macro-builder root).
#   out:               Output filename (the fixed link stored in artifacts folder).
#   type:              can | usb | sd
#   mcu_alias, mcu_alias1, ... :
#                      One or more aliases matching [mcu <alias>] sections in printer.cfg.
#                      Use 'main' to refer to the base [mcu] section (no alias).
#   flash terminal:    ssh | gcode_shell
#                      How to print the suggested flashing commands (N/A for sd).
#
# Notes:
# - CAN sections will print 'flash_can.py' suggestions (or RUN_SHELL_COMMAND via gcode).
# - USB sections will print 'flashtool.py' (or legacy 'flashtool.py') suggestions (or RUN_SHELL_COMMAND via gcode).
# - SD sections print manual steps (copy to microSD root and power-cycle).
#
# ------- EXAMPLE: KLIPPER over CAN (two toolheads) -------
[klipper EBB36]
name: EBB36
config: ebb36_can.config
out: ebb.bin
type: can
mcu_alias: ebb1
mcu_alias1: ebb2
flash terminal: gcode_shell

# ------- EXAMPLE: KLIPPER via SD (main board) -------
[klipper MAIN]
name: MAIN
config: main_mcu.config
out: mks_monster8.bin
type: sd
mcu_alias: main
# flash terminal: (not applicable to sd)

# ------- EXAMPLE: KATAPULT over CAN (toolheads bootloader) -------
[katapult EBB36]
name: EBB36
config: ebb36_can.config
out: ebb.bin
type: can
mcu_alias: ebb1
mcu_alias1: ebb2
flash terminal: ssh
EOF
echo "[5/6] builder.cfg created at ${BUILDER_CFG} (backup saved if existed)."

# -------------------------------------------------
# 6) Hide non-user macros (buttons)
# -------------------------------------------------
# In Web UI, ONLY 'gcode_macro' blocks become buttons.
# FLASH_CAN / FLASH_USB are 'gcode_shell_command', so they do not show as buttons.
echo "[6/6] Flash backends are gcode_shell_command (not shown as buttons)."

echo
echo "=== Done ==="
echo "• builder_macros.cfg: ${BUILDER_MACROS} (copied from repo examples and included in printer.cfg)"
echo "• builder.cfg:        ${BUILDER_CFG} (edit to suit your setup)"
echo "• Restart Klipper after installation:"
echo "    sudo systemctl restart klipper"
